steps:
  - script: |
      dotnet restore
      dotnet build --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration Release --output $(System.DefaultWorkingDirectory)/publish_output'
      projects: '**/*StorageFunction.csproj'
      publishWebProjects: false
      modifyOutputPath: true
      zipAfterPublish: false
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output/StorageFunction'
      includeRootFolder: false
      archiveFile: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
  - script: dotnet test StorageFunctionTests --logger trx
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      name: 'drop'
